
import { CoffeeItem, Promotion } from './types';

export const MENU_ITEMS: CoffeeItem[] = [
  // --- MENU BARU (Halaman 4 & 5) ---
  {
    id: 101,
    name: 'Butter Cream Sea Salt Latte',
    description: 'Koleksi terbaru Butter Cream dengan sentuhan rasa Sea Salt.',
    details: 'Bagian dari Butter Cream Collection. Tekstur foam yang tebal, gurih, dan creamy di atas espresso premium.',
    price: 28000,
    imageUrl: '/assets/menu/beverages/butter-cream-sea-salt-latte.jpg',
    category: 'new',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 102,
    name: 'Caramel Priline Machiatto',
    description: 'Koleksi terbaru Butter Cream dengan rasa Caramel Priline.',
    details: 'Manisnya caramel priline berpadu dengan kelembutan butter cream di setiap sesapan.',
    price: 28000,
    imageUrl: '/assets/menu/beverages/caramel-priline-machiatto.jpg',
    category: 'new',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 103,
    name: 'Es Teler Azzahra',
    description: 'Menu baru Es Teler spesial dengan porsi melimpah.',
    details: 'Campuran alpukat, nangka, kelapa muda, dan mutiara dalam kuah susu rahasia Azzahra yang segar.',
    price: 25000,
    imageUrl: '/assets/menu/beverages/es-teler-azzahra.jpg',
    category: 'new',
    type: 'beverage',
    stock: 999,
  },

  // --- MINUMAN (Halaman 2) ---
  {
    id: 1,
    name: 'Kopi Hitam',
    description: 'Kopi hitam murni khas Azzahra.',
    details: 'Biji kopi pilihan yang diseduh dengan teknik tradisional untuk aroma yang kuat.',
    price: 10000,
    imageUrl: '/assets/menu/beverages/kopi-hitam.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 2,
    name: 'Hitam Aren',
    description: 'Kopi hitam dengan manisnya gula aren asli.',
    details: 'Cita rasa kopi pahit yang diseimbangkan oleh manis alami gula aren.',
    price: 12000,
    imageUrl: '/assets/menu/beverages/hitam-aren.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 3,
    name: 'Kopi Susu K',
    description: 'Kopi susu porsi kecil (K).',
    details: 'Kopi susu nikmat dengan takaran yang pas untuk teman santai.',
    price: 12000,
    imageUrl: '/assets/menu/beverages/kopi-susu-k.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 4,
    name: 'Kopi Susu B',
    description: 'Kopi susu porsi besar (B).',
    details: 'Kepuasan lebih dengan ukuran cup yang lebih besar dan rasa yang lebih mantap.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/kopi-susu-b.jpg',
    category: 'best-seller',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 5,
    name: 'Kopi Latte',
    description: 'Espresso dengan susu yang lembut.',
    details: 'Tekstur susu yang halus berpadu sempurna dengan espresso premium.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/kopi-latte.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 6,
    name: 'Coffee Bottle (Take Away)',
    description: 'Kopi signature dalam kemasan botol praktis.',
    details: 'Bawa pulang kesegaran kopi Azzahra untuk dinikmati kapan saja.',
    price: 22000,
    imageUrl: '/assets/menu/beverages/coffee-bottle.jpg',
    category: 'best-seller',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 7,
    name: 'Ice Kopi Aren',
    description: 'Kopi susu gula aren dingin yang menyegarkan.',
    details: 'Pilihan paling favorit bagi pecinta kopi susu dingin dengan gula aren.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/ice-kopi-aren.jpg',
    category: 'best-seller',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 8,
    name: 'Hazelnut Latte',
    description: 'Kopi susu dengan aroma hazelnut yang memikat.',
    details: 'Sentuhan rasa kacang yang gurih dalam segelas latte dingin.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/hazelnut-latte.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 9,
    name: 'Caramelized Latte',
    description: 'Latte dengan manis karamel yang kaya.',
    details: 'Rasa karamel yang mewah menyelimuti setiap tegukan kopi Anda.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/caramelized-latte.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 10,
    name: 'Vanilla Latte',
    description: 'Kopi susu dengan rasa vanila yang klasik.',
    details: 'Kelembutan vanila yang berpadu serasi dengan susu dan kopi.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/vanilla-latte.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 11,
    name: 'Chocolate',
    description: 'Minuman cokelat kental dan manis.',
    details: 'Cokelat premium yang disajikan dingin untuk mood booster Anda.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/chocolate.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 12,
    name: 'Ice/Hot Tea',
    description: 'Teh manis segar, tersedia dingin atau panas.',
    details: 'Kesegaran teh pilihan dengan gula asli.',
    price: 5000,
    imageUrl: '/assets/menu/beverages/ice-hot-tea.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 13,
    name: 'Thaitea',
    description: 'Teh Thailand dengan campuran susu kental manis.',
    details: 'Rasa teh Thailand yang autentik dan sangat creamy.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/thaitea.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 14,
    name: 'Greentea',
    description: 'Teh hijau susu (Matcha) yang menenangkan.',
    details: 'Aroma matcha yang khas berpadu dengan susu segar.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/greentea.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 15,
    name: 'Milk Tea',
    description: 'Teh susu klasik yang nikmat.',
    details: 'Perpaduan sempurna antara seduhan teh dan susu kental manis.',
    price: 12000,
    imageUrl: '/assets/menu/beverages/milk-tea.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 16,
    name: 'Lemon Tea',
    description: 'Teh lemon segar yang asam manis.',
    details: 'Kesegaran lemon asli dalam setiap tegukan teh dingin.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/lemon-tea.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 17,
    name: 'Lychee Tea',
    description: 'Teh leci dengan buah leci asli.',
    details: 'Teh dingin yang harum dengan rasa buah leci yang manis.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/lychee-tea.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 18,
    name: 'Korean Blue Berry',
    description: 'Minuman susu blueberry ala Korea yang estetik.',
    details: 'Warna biru cantik dari blueberry dengan rasa susu yang kental.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/korean-blue-berry.jpg',
    category: 'new',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 19,
    name: 'Korean Strawberry',
    description: 'Susu stroberi dengan potongan buah asli.',
    details: 'Rasa stroberi yang manis dan segar dalam balutan susu dingin.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/korean-strawberry.jpg',
    category: 'new',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 20,
    name: 'Korean Manggo Milk',
    description: 'Susu mangga dengan tekstur yang lembut.',
    details: 'Kelezatan buah mangga matang yang berpadu dengan susu ala Korea.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/korean-manggo-milk.jpg',
    category: 'new',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 21,
    name: 'Orange Yakult',
    description: 'Jus jeruk segar dengan campuran Yakult.',
    details: 'Minuman sehat probiotik dengan rasa asam manis yang pas.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/orange-yakult.jpg',
    category: 'best-seller',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 22,
    name: 'Ice Sogem',
    description: 'Susu Gembira dingin (Soda Gembira).',
    details: 'Klasik yang selalu dicari, susu kental manis dengan soda dan sirup.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/ice-sogem.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 23,
    name: 'Lychee Yakult',
    description: 'Campuran rasa leci dengan manfaat Yakult.',
    details: 'Segar dan menyehatkan bagi pencernaan Anda.',
    price: 15000,
    imageUrl: '/assets/menu/beverages/lychee-yakult.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 24,
    name: 'Buah Naga (Jus)',
    description: 'Jus buah naga merah asli.',
    details: 'Tanpa pemanis buatan, murni dari kesegaran buah naga.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/buah-naga-jus.jpg',
    category: 'best-seller',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 25,
    name: 'Buah Mangga (Jus)',
    description: 'Jus mangga kental yang manis.',
    details: 'Dibuat dari mangga pilihan yang matang sempurna.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/buah-mangga-jus.jpg',
    category: 'best-seller',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 26,
    name: 'Buah Avocado (Jus)',
    description: 'Jus alpukat yang creamy dan mengenyangkan.',
    details: 'Dilengkapi dengan sirup cokelat untuk rasa yang lebih mantap.',
    price: 20000,
    imageUrl: '/assets/menu/beverages/buah-avocado-jus.jpg',
    category: 'best-seller',
    type: 'beverage',
    stock: 999,
  },
  {
    id: 27,
    name: 'Jeruk Peras',
    description: 'Minuman jeruk peras segar murni.',
    details: 'Vitamin C alami dalam setiap perasan jeruk segar.',
    price: 10000,
    imageUrl: '/assets/menu/beverages/jeruk-peras.jpg',
    category: 'standard',
    type: 'beverage',
    stock: 999,
  },

  // --- MAKANAN (Halaman 3) ---
  {
    id: 50,
    name: 'Sop Saudara',
    description: 'Spesialis Sop Saudara khas Azzahra.',
    details: 'Potongan daging sapi empuk dengan kuah rempah yang kaya rasa. Favorit sepanjang masa.',
    price: 12000,
    imageUrl: '/assets/menu/foods/sop-saudara.jpg',
    category: 'best-seller',
    type: 'food',
    stock: 999,
  },
  {
    id: 51,
    name: 'Nasi Campur',
    description: 'Porsi nasi campur dengan lauk komplit.',
    details: 'Satu piring penuh kebahagiaan dengan berbagai lauk pilihan.',
    price: 25000,
    imageUrl: '/assets/menu/foods/nasi-campur.jpg',
    category: 'best-seller',
    type: 'food',
    stock: 999,
  },
  {
    id: 52,
    name: 'Nasi Kuning',
    description: 'Nasi kuning gurih dengan bumbu rempah melimpah.',
    details: 'Disajikan hangat dengan lauk pelengkap khas warkop.',
    price: 25000,
    imageUrl: '/assets/menu/foods/nasi-kuning.jpg',
    category: 'best-seller',
    type: 'food',
    stock: 999,
  },
  {
    id: 53,
    name: 'Nasi Ayam Goreng',
    description: 'Paket nasi dengan ayam goreng krispi.',
    details: 'Ayam ungkep bumbu rempah yang digoreng hingga garing keemasan.',
    price: 25000,
    imageUrl: '/assets/menu/foods/nasi-ayam-goreng.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 54,
    name: 'Nasi Goreng Merah / Kampung',
    description: 'Nasi goreng dengan bumbu khas rahasia.',
    details: 'Tersedia varian merah yang pedas nikmat atau kampung yang gurih.',
    price: 25000,
    imageUrl: '/assets/menu/foods/nasi-goreng-merah-kampung.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 55,
    name: 'Nasi Rawon',
    description: 'Rawon daging sapi dengan kuah hitam kental.',
    details: 'Kelezatan daging sapi dalam kuah kluwek yang kaya akan rempah.',
    price: 25000,
    imageUrl: '/assets/menu/foods/nasi-rawon.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 56,
    name: 'Paket Ikan Goreng',
    description: 'Nasi dengan ikan goreng segar dan sambal.',
    details: 'Ikan goreng garing yang disajikan dengan sambal terasi pedas.',
    price: 20000,
    imageUrl: '/assets/menu/foods/paket-ikan-goreng.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 57,
    name: 'Indomie Goreng',
    description: 'Indomie goreng legendaris dengan topping.',
    details: 'Mie instan favorit sejuta umat, disajikan dengan telur dan sayuran.',
    price: 12000,
    imageUrl: '/assets/menu/foods/indomie-goreng.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 58,
    name: 'Indomie Kuah/Soto',
    description: 'Indomie kuah hangat rasa soto.',
    details: 'Pilihan hangat saat cuaca hujan, mie kuah dengan rasa jeruk nipis segar.',
    price: 8000,
    imageUrl: '/assets/menu/foods/indomie-kuah-soto.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 59,
    name: 'Mie Kuah / Mie Goreng Jawa',
    description: 'Mie olahan dengan sayuran dan telur.',
    details: 'Mie masak tradisional dengan bumbu gurih yang meresap.',
    price: 20000,
    imageUrl: '/assets/menu/foods/mie-kuah-mie-goreng-jawa.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 60,
    name: 'Roti Bakar',
    description: 'Roti bakar empuk dengan aneka topping.',
    details: 'Camilan manis yang cocok untuk menemani kopi Anda.',
    price: 10000,
    imageUrl: '/assets/menu/foods/roti-bakar.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 61,
    name: 'Pisang Goreng Palm Sugar Susu',
    description: 'Pisang goreng renyah dengan taburan gula palem.',
    details: 'Kombinasi manis dari palm sugar dan susu kental manis di atas pisang hangat.',
    price: 15000,
    imageUrl: '/assets/menu/foods/pisang-goreng-palm-sugar-susu.jpg',
    category: 'best-seller',
    type: 'food',
    stock: 999,
  },
  {
    id: 62,
    name: 'Pisang Goreng Coklat Keju',
    description: 'Topping coklat dan keju yang melimpah.',
    details: 'Favorit sepanjang masa, pisang goreng dengan parutan keju dan coklat.',
    price: 15000,
    imageUrl: '/assets/menu/foods/pisang-goreng-coklat-keju.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 63,
    name: 'Pisang Goreng Lombok/Mentega',
    description: 'Sensasi gurih pisang goreng mentega.',
    details: 'Pisang goreng dengan sentuhan mentega yang gurih dan sambal cocolan.',
    price: 15000,
    imageUrl: '/assets/menu/foods/pisang-goreng-lombok-mentega.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
  {
    id: 64,
    name: 'Pisang Peppe',
    description: 'Pisang peppe tradisional khas yang dipukul tipis.',
    details: 'Sajian unik pisang tipis renyah dengan sambal pedas.',
    price: 15000,
    imageUrl: '/assets/menu/foods/pisang-peppe.jpg',
    category: 'best-seller',
    type: 'food',
    stock: 999,
  },
  {
    id: 65,
    name: 'Ubi Goreng',
    description: 'Ubi goreng hangat yang manis dan gurih.',
    details: 'Potongan ubi pilihan yang digoreng hingga garing keemasan.',
    price: 15000,
    imageUrl: '/assets/menu/foods/ubi-goreng.jpg',
    category: 'standard',
    type: 'food',
    stock: 999,
  },
];

export const PROMOTIONS_LIST: Promotion[] = [
  {
    id: 1,
    title: 'Butter Cream Series',
    description: 'Nikmati kemewahan Butter Cream Collection terbaru kami (Sea Salt & Caramel) hanya Rp 28.000.',
    imageUrl: '/assets/menu/promotions/butter-cream-series.jpg',
  },
  {
    id: 2,
    title: 'Segarnya Es Teler',
    description: 'Es Teler Azzahra yang melimpah buahnya, segar kuahnya. Porsi besar hanya Rp 25.000!',
    imageUrl: '/assets/menu/promotions/segarnya-es-teler.jpg',
  }
];
